@extends('layouts.main')

@section('content')
    <h1>Homepage</h1>
    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum posuere sapien hendrerit lobortis iaculis. Mauris non sodales quam. Quisque eget risus sed dolor sagittis porta ut at ipsum. Pellentesque in tempor mauris, eget viverra nibh. Integer rhoncus mi id purus interdum, id scelerisque dolor porta. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nunc magna augue, mattis eu accumsan at, laoreet ut felis. Nam tristique nulla nisi, quis cursus nunc volutpat nec. Cras ornare sit amet augue ut viverra. In placerat ligula eu massa cursus tincidunt. Fusce euismod, neque at tincidunt consectetur, massa ex aliquet dui, non euismod massa felis et purus. Morbi a nunc neque.</p>
    <p>Phasellus consectetur aliquet sollicitudin. Quisque molestie, justo vel sodales facilisis, leo velit tincidunt augue, non imperdiet eros arcu quis metus. Vestibulum lacinia velit dolor. Quisque in fermentum eros. Morbi iaculis, eros eleifend fringilla efficitur, erat tortor finibus est, dignissim bibendum felis mauris ut augue. Aliquam volutpat viverra tincidunt. Maecenas pretium metus purus, mattis maximus lorem rutrum quis. Nullam vel congue ante. Vivamus placerat interdum faucibus. Morbi aliquet tristique elit, interdum placerat dui ornare luctus.</p>
    <p>Curabitur blandit nec ex quis tempor. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Suspendisse varius venenatis ex sed semper. Mauris pretium, urna id venenatis lacinia, metus magna vulputate ex, sagittis vulputate tellus nibh ut diam. Nunc erat erat, aliquam dignissim sollicitudin sit amet, tristique vitae dui. Phasellus in dictum erat, quis convallis diam. Nullam tincidunt lectus lorem, sit amet tincidunt urna tempor vel. Donec pulvinar libero at neque faucibus, quis cursus dui rhoncus. Proin mi metus, mollis eu volutpat sit amet, laoreet sed risus. Pellentesque et tortor dui. Nulla non blandit mauris. Pellentesque venenatis nec diam ut vulputate. Etiam ipsum lorem, tristique non egestas in, condimentum vel tortor.</p>
    <p>Mauris non mauris quam. Ut ac venenatis mauris. Morbi dapibus lacinia luctus. Aenean lobortis, sapien at condimentum accumsan, neque arcu hendrerit leo, et rutrum tortor justo vel felis. Sed non sem ac libero tempus consequat. Pellentesque lacinia convallis varius. Sed luctus faucibus neque ac finibus.</p>
    <p>Curabitur congue sapien id libero ultricies, sodales pellentesque enim pharetra. Duis lectus purus, aliquet et nisl et, volutpat tristique nisl. Sed lobortis sed lorem sit amet ornare. Ut vehicula ante et est vehicula, mollis varius ligula gravida. Nunc at massa fermentum, consectetur lectus a, pharetra enim. Sed efficitur feugiat porttitor. Suspendisse imperdiet, purus ac volutpat bibendum, eros magna suscipit dui, pretium luctus mauris tellus et est. Aliquam sed nisi a nibh egestas commodo. Aenean id quam sem. Sed feugiat consequat rutrum. Nulla maximus odio justo, ut porttitor enim dignissim ut.</p>
@endsection